# Generated by Django 2.2 on 2019-04-27 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='CPF',
            field=models.CharField(max_length=128, unique=True),
        ),
    ]
